/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.telemetry.Telemetry', null, global);
goog.exportSymbol('proto.telemetry.TelemetryField', null, global);
goog.exportSymbol('proto.telemetry.TelemetryGPBTable', null, global);
goog.exportSymbol('proto.telemetry.TelemetryRowGPB', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.telemetry.Telemetry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.telemetry.Telemetry.repeatedFields_, proto.telemetry.Telemetry.oneofGroups_);
};
goog.inherits(proto.telemetry.Telemetry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.telemetry.Telemetry.displayName = 'proto.telemetry.Telemetry';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.telemetry.Telemetry.repeatedFields_ = [11];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.telemetry.Telemetry.oneofGroups_ = [[1],[3]];

/**
 * @enum {number}
 */
proto.telemetry.Telemetry.NodeIdCase = {
  NODE_ID_NOT_SET: 0,
  NODE_ID_STR: 1
};

/**
 * @return {proto.telemetry.Telemetry.NodeIdCase}
 */
proto.telemetry.Telemetry.prototype.getNodeIdCase = function() {
  return /** @type {proto.telemetry.Telemetry.NodeIdCase} */(jspb.Message.computeOneofCase(this, proto.telemetry.Telemetry.oneofGroups_[0]));
};

/**
 * @enum {number}
 */
proto.telemetry.Telemetry.SubscriptionCase = {
  SUBSCRIPTION_NOT_SET: 0,
  SUBSCRIPTION_ID_STR: 3
};

/**
 * @return {proto.telemetry.Telemetry.SubscriptionCase}
 */
proto.telemetry.Telemetry.prototype.getSubscriptionCase = function() {
  return /** @type {proto.telemetry.Telemetry.SubscriptionCase} */(jspb.Message.computeOneofCase(this, proto.telemetry.Telemetry.oneofGroups_[1]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.telemetry.Telemetry.prototype.toObject = function(opt_includeInstance) {
  return proto.telemetry.Telemetry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.telemetry.Telemetry} msg The msg instance to transform.
 * @return {!Object}
 */
proto.telemetry.Telemetry.toObject = function(includeInstance, msg) {
  var f, obj = {
    nodeIdStr: jspb.Message.getField(msg, 1),
    subscriptionIdStr: jspb.Message.getField(msg, 3),
    encodingPath: msg.getEncodingPath(),
    collectionId: msg.getCollectionId(),
    collectionStartTime: msg.getCollectionStartTime(),
    msgTimestamp: msg.getMsgTimestamp(),
    dataGpbkvList: jspb.Message.toObjectList(msg.getDataGpbkvList(),
    proto.telemetry.TelemetryField.toObject, includeInstance),
    dataGpb: (f = msg.getDataGpb()) && proto.telemetry.TelemetryGPBTable.toObject(includeInstance, f),
    collectionEndTime: msg.getCollectionEndTime()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.telemetry.Telemetry}
 */
proto.telemetry.Telemetry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.telemetry.Telemetry;
  return proto.telemetry.Telemetry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.telemetry.Telemetry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.telemetry.Telemetry}
 */
proto.telemetry.Telemetry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeIdStr(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubscriptionIdStr(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setEncodingPath(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCollectionId(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCollectionStartTime(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMsgTimestamp(value);
      break;
    case 11:
      var value = new proto.telemetry.TelemetryField;
      reader.readMessage(value,proto.telemetry.TelemetryField.deserializeBinaryFromReader);
      msg.getDataGpbkvList().push(value);
      msg.setDataGpbkvList(msg.getDataGpbkvList());
      break;
    case 12:
      var value = new proto.telemetry.TelemetryGPBTable;
      reader.readMessage(value,proto.telemetry.TelemetryGPBTable.deserializeBinaryFromReader);
      msg.setDataGpb(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCollectionEndTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.telemetry.Telemetry} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.telemetry.Telemetry.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.telemetry.Telemetry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.telemetry.Telemetry.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = jspb.Message.getField(this, 1);
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = jspb.Message.getField(this, 3);
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getEncodingPath();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = this.getCollectionId();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = this.getCollectionStartTime();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
  f = this.getMsgTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = this.getDataGpbkvList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.telemetry.TelemetryField.serializeBinaryToWriter
    );
  }
  f = this.getDataGpb();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.telemetry.TelemetryGPBTable.serializeBinaryToWriter
    );
  }
  f = this.getCollectionEndTime();
  if (f !== 0) {
    writer.writeUint64(
      13,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.telemetry.Telemetry} The clone.
 */
proto.telemetry.Telemetry.prototype.cloneMessage = function() {
  return /** @type {!proto.telemetry.Telemetry} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string node_id_str = 1;
 * @return {string}
 */
proto.telemetry.Telemetry.prototype.getNodeIdStr = function() {
  return /** @type {string} */ (!this.hasNodeIdStr() ? "" : jspb.Message.getField(this, 1));
};


/** @param {string?|undefined} value  */
proto.telemetry.Telemetry.prototype.setNodeIdStr = function(value) {
  jspb.Message.setOneofField(this, 1, proto.telemetry.Telemetry.oneofGroups_[0], value);
};


proto.telemetry.Telemetry.prototype.clearNodeIdStr = function() {
  jspb.Message.setOneofField(this, 1, proto.telemetry.Telemetry.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.Telemetry.prototype.hasNodeIdStr = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string subscription_id_str = 3;
 * @return {string}
 */
proto.telemetry.Telemetry.prototype.getSubscriptionIdStr = function() {
  return /** @type {string} */ (!this.hasSubscriptionIdStr() ? "" : jspb.Message.getField(this, 3));
};


/** @param {string?|undefined} value  */
proto.telemetry.Telemetry.prototype.setSubscriptionIdStr = function(value) {
  jspb.Message.setOneofField(this, 3, proto.telemetry.Telemetry.oneofGroups_[1], value);
};


proto.telemetry.Telemetry.prototype.clearSubscriptionIdStr = function() {
  jspb.Message.setOneofField(this, 3, proto.telemetry.Telemetry.oneofGroups_[1], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.Telemetry.prototype.hasSubscriptionIdStr = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string encoding_path = 6;
 * @return {string}
 */
proto.telemetry.Telemetry.prototype.getEncodingPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 6, ""));
};


/** @param {string} value  */
proto.telemetry.Telemetry.prototype.setEncodingPath = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional uint64 collection_id = 8;
 * @return {number}
 */
proto.telemetry.Telemetry.prototype.getCollectionId = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 8, 0));
};


/** @param {number} value  */
proto.telemetry.Telemetry.prototype.setCollectionId = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional uint64 collection_start_time = 9;
 * @return {number}
 */
proto.telemetry.Telemetry.prototype.getCollectionStartTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 9, 0));
};


/** @param {number} value  */
proto.telemetry.Telemetry.prototype.setCollectionStartTime = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional uint64 msg_timestamp = 10;
 * @return {number}
 */
proto.telemetry.Telemetry.prototype.getMsgTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 10, 0));
};


/** @param {number} value  */
proto.telemetry.Telemetry.prototype.setMsgTimestamp = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * repeated TelemetryField data_gpbkv = 11;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.telemetry.TelemetryField>}
 */
proto.telemetry.Telemetry.prototype.getDataGpbkvList = function() {
  return /** @type{!Array.<!proto.telemetry.TelemetryField>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.telemetry.TelemetryField, 11));
};


/** @param {Array.<!proto.telemetry.TelemetryField>} value  */
proto.telemetry.Telemetry.prototype.setDataGpbkvList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 11, value);
};


proto.telemetry.Telemetry.prototype.clearDataGpbkvList = function() {
  this.setDataGpbkvList([]);
};


/**
 * optional TelemetryGPBTable data_gpb = 12;
 * @return {proto.telemetry.TelemetryGPBTable}
 */
proto.telemetry.Telemetry.prototype.getDataGpb = function() {
  return /** @type{proto.telemetry.TelemetryGPBTable} */ (
    jspb.Message.getWrapperField(this, proto.telemetry.TelemetryGPBTable, 12));
};


/** @param {proto.telemetry.TelemetryGPBTable|undefined} value  */
proto.telemetry.Telemetry.prototype.setDataGpb = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.telemetry.Telemetry.prototype.clearDataGpb = function() {
  this.setDataGpb(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.Telemetry.prototype.hasDataGpb = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional uint64 collection_end_time = 13;
 * @return {number}
 */
proto.telemetry.Telemetry.prototype.getCollectionEndTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 13, 0));
};


/** @param {number} value  */
proto.telemetry.Telemetry.prototype.setCollectionEndTime = function(value) {
  jspb.Message.setField(this, 13, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.telemetry.TelemetryField = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.telemetry.TelemetryField.repeatedFields_, proto.telemetry.TelemetryField.oneofGroups_);
};
goog.inherits(proto.telemetry.TelemetryField, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.telemetry.TelemetryField.displayName = 'proto.telemetry.TelemetryField';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.telemetry.TelemetryField.repeatedFields_ = [15];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.telemetry.TelemetryField.oneofGroups_ = [[4,5,6,7,8,9,10,11,12]];

/**
 * @enum {number}
 */
proto.telemetry.TelemetryField.ValueByTypeCase = {
  VALUE_BY_TYPE_NOT_SET: 0,
  BYTES_VALUE: 4,
  STRING_VALUE: 5,
  BOOL_VALUE: 6,
  UINT32_VALUE: 7,
  UINT64_VALUE: 8,
  SINT32_VALUE: 9,
  SINT64_VALUE: 10,
  DOUBLE_VALUE: 11,
  FLOAT_VALUE: 12
};

/**
 * @return {proto.telemetry.TelemetryField.ValueByTypeCase}
 */
proto.telemetry.TelemetryField.prototype.getValueByTypeCase = function() {
  return /** @type {proto.telemetry.TelemetryField.ValueByTypeCase} */(jspb.Message.computeOneofCase(this, proto.telemetry.TelemetryField.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.telemetry.TelemetryField.prototype.toObject = function(opt_includeInstance) {
  return proto.telemetry.TelemetryField.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.telemetry.TelemetryField} msg The msg instance to transform.
 * @return {!Object}
 */
proto.telemetry.TelemetryField.toObject = function(includeInstance, msg) {
  var f, obj = {
    timestamp: msg.getTimestamp(),
    name: msg.getName(),
    bytesValue: msg.getBytesValue_asB64(),
    stringValue: jspb.Message.getField(msg, 5),
    boolValue: jspb.Message.getField(msg, 6),
    uint32Value: jspb.Message.getField(msg, 7),
    uint64Value: jspb.Message.getField(msg, 8),
    sint32Value: jspb.Message.getField(msg, 9),
    sint64Value: jspb.Message.getField(msg, 10),
    doubleValue: jspb.Message.getOptionalFloatingPointField(msg, 11),
    floatValue: jspb.Message.getOptionalFloatingPointField(msg, 12),
    fieldsList: jspb.Message.toObjectList(msg.getFieldsList(),
    proto.telemetry.TelemetryField.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.telemetry.TelemetryField}
 */
proto.telemetry.TelemetryField.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.telemetry.TelemetryField;
  return proto.telemetry.TelemetryField.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.telemetry.TelemetryField} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.telemetry.TelemetryField}
 */
proto.telemetry.TelemetryField.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBytesValue(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringValue(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolValue(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUint32Value(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUint64Value(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setSint32Value(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setSint64Value(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDoubleValue(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setFloatValue(value);
      break;
    case 15:
      var value = new proto.telemetry.TelemetryField;
      reader.readMessage(value,proto.telemetry.TelemetryField.deserializeBinaryFromReader);
      msg.getFieldsList().push(value);
      msg.setFieldsList(msg.getFieldsList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.telemetry.TelemetryField} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.telemetry.TelemetryField.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.telemetry.TelemetryField.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.telemetry.TelemetryField.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = jspb.Message.getField(this, 4);
  if (f != null) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = jspb.Message.getField(this, 5);
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = jspb.Message.getField(this, 6);
  if (f != null) {
    writer.writeBool(
      6,
      f
    );
  }
  f = jspb.Message.getField(this, 7);
  if (f != null) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = jspb.Message.getField(this, 8);
  if (f != null) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = jspb.Message.getField(this, 9);
  if (f != null) {
    writer.writeSint32(
      9,
      f
    );
  }
  f = jspb.Message.getField(this, 10);
  if (f != null) {
    writer.writeSint64(
      10,
      f
    );
  }
  f = jspb.Message.getField(this, 11);
  if (f != null) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = jspb.Message.getField(this, 12);
  if (f != null) {
    writer.writeFloat(
      12,
      f
    );
  }
  f = this.getFieldsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      proto.telemetry.TelemetryField.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.telemetry.TelemetryField} The clone.
 */
proto.telemetry.TelemetryField.prototype.cloneMessage = function() {
  return /** @type {!proto.telemetry.TelemetryField} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional uint64 timestamp = 1;
 * @return {number}
 */
proto.telemetry.TelemetryField.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.telemetry.TelemetryField.prototype.setTimestamp = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.telemetry.TelemetryField.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.telemetry.TelemetryField.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bytes bytes_value = 4;
 * @return {(string|Uint8Array)}
 */
proto.telemetry.TelemetryField.prototype.getBytesValue = function() {
  return /** @type {(string|Uint8Array)} */ (!this.hasBytesValue() ? "" : jspb.Message.getField(this, 4));
};


/**
 * optional bytes bytes_value = 4;
 * This is a type-conversion wrapper around `getBytesValue()`
 * @return {string}
 */
proto.telemetry.TelemetryField.prototype.getBytesValue_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBytesValue()));
};


/**
 * optional bytes bytes_value = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytesValue()`
 * @return {Uint8Array}
 */
proto.telemetry.TelemetryField.prototype.getBytesValue_asU8 = function() {
  return /** @type {Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBytesValue()));
};


/** @param {(string|Uint8Array)|undefined} value  */
proto.telemetry.TelemetryField.prototype.setBytesValue = function(value) {
  jspb.Message.setOneofField(this, 4, proto.telemetry.TelemetryField.oneofGroups_[0], value);
};


proto.telemetry.TelemetryField.prototype.clearBytesValue = function() {
  jspb.Message.setOneofField(this, 4, proto.telemetry.TelemetryField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.TelemetryField.prototype.hasBytesValue = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string string_value = 5;
 * @return {string}
 */
proto.telemetry.TelemetryField.prototype.getStringValue = function() {
  return /** @type {string} */ (!this.hasStringValue() ? "" : jspb.Message.getField(this, 5));
};


/** @param {string?|undefined} value  */
proto.telemetry.TelemetryField.prototype.setStringValue = function(value) {
  jspb.Message.setOneofField(this, 5, proto.telemetry.TelemetryField.oneofGroups_[0], value);
};


proto.telemetry.TelemetryField.prototype.clearStringValue = function() {
  jspb.Message.setOneofField(this, 5, proto.telemetry.TelemetryField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.TelemetryField.prototype.hasStringValue = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool bool_value = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.telemetry.TelemetryField.prototype.getBoolValue = function() {
  return /** @type {boolean} */ (!this.hasBoolValue() ? false : jspb.Message.getField(this, 6));
};


/** @param {boolean?|undefined} value  */
proto.telemetry.TelemetryField.prototype.setBoolValue = function(value) {
  jspb.Message.setOneofField(this, 6, proto.telemetry.TelemetryField.oneofGroups_[0], value);
};


proto.telemetry.TelemetryField.prototype.clearBoolValue = function() {
  jspb.Message.setOneofField(this, 6, proto.telemetry.TelemetryField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.TelemetryField.prototype.hasBoolValue = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional uint32 uint32_value = 7;
 * @return {number}
 */
proto.telemetry.TelemetryField.prototype.getUint32Value = function() {
  return /** @type {number} */ (!this.hasUint32Value() ? 0 : jspb.Message.getField(this, 7));
};


/** @param {number?|undefined} value  */
proto.telemetry.TelemetryField.prototype.setUint32Value = function(value) {
  jspb.Message.setOneofField(this, 7, proto.telemetry.TelemetryField.oneofGroups_[0], value);
};


proto.telemetry.TelemetryField.prototype.clearUint32Value = function() {
  jspb.Message.setOneofField(this, 7, proto.telemetry.TelemetryField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.TelemetryField.prototype.hasUint32Value = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional uint64 uint64_value = 8;
 * @return {number}
 */
proto.telemetry.TelemetryField.prototype.getUint64Value = function() {
  return /** @type {number} */ (!this.hasUint64Value() ? 0 : jspb.Message.getField(this, 8));
};


/** @param {number?|undefined} value  */
proto.telemetry.TelemetryField.prototype.setUint64Value = function(value) {
  jspb.Message.setOneofField(this, 8, proto.telemetry.TelemetryField.oneofGroups_[0], value);
};


proto.telemetry.TelemetryField.prototype.clearUint64Value = function() {
  jspb.Message.setOneofField(this, 8, proto.telemetry.TelemetryField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.TelemetryField.prototype.hasUint64Value = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional sint32 sint32_value = 9;
 * @return {number}
 */
proto.telemetry.TelemetryField.prototype.getSint32Value = function() {
  return /** @type {number} */ (!this.hasSint32Value() ? 0 : jspb.Message.getField(this, 9));
};


/** @param {number?|undefined} value  */
proto.telemetry.TelemetryField.prototype.setSint32Value = function(value) {
  jspb.Message.setOneofField(this, 9, proto.telemetry.TelemetryField.oneofGroups_[0], value);
};


proto.telemetry.TelemetryField.prototype.clearSint32Value = function() {
  jspb.Message.setOneofField(this, 9, proto.telemetry.TelemetryField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.TelemetryField.prototype.hasSint32Value = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional sint64 sint64_value = 10;
 * @return {number}
 */
proto.telemetry.TelemetryField.prototype.getSint64Value = function() {
  return /** @type {number} */ (!this.hasSint64Value() ? 0 : jspb.Message.getField(this, 10));
};


/** @param {number?|undefined} value  */
proto.telemetry.TelemetryField.prototype.setSint64Value = function(value) {
  jspb.Message.setOneofField(this, 10, proto.telemetry.TelemetryField.oneofGroups_[0], value);
};


proto.telemetry.TelemetryField.prototype.clearSint64Value = function() {
  jspb.Message.setOneofField(this, 10, proto.telemetry.TelemetryField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.TelemetryField.prototype.hasSint64Value = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional double double_value = 11;
 * @return {number}
 */
proto.telemetry.TelemetryField.prototype.getDoubleValue = function() {
  return /** @type {number} */ (!this.hasDoubleValue() ? 0.0 : +jspb.Message.getField(this, 11));
};


/** @param {number?|undefined} value  */
proto.telemetry.TelemetryField.prototype.setDoubleValue = function(value) {
  jspb.Message.setOneofField(this, 11, proto.telemetry.TelemetryField.oneofGroups_[0], value);
};


proto.telemetry.TelemetryField.prototype.clearDoubleValue = function() {
  jspb.Message.setOneofField(this, 11, proto.telemetry.TelemetryField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.TelemetryField.prototype.hasDoubleValue = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional float float_value = 12;
 * @return {number}
 */
proto.telemetry.TelemetryField.prototype.getFloatValue = function() {
  return /** @type {number} */ (!this.hasFloatValue() ? 0.0 : +jspb.Message.getField(this, 12));
};


/** @param {number?|undefined} value  */
proto.telemetry.TelemetryField.prototype.setFloatValue = function(value) {
  jspb.Message.setOneofField(this, 12, proto.telemetry.TelemetryField.oneofGroups_[0], value);
};


proto.telemetry.TelemetryField.prototype.clearFloatValue = function() {
  jspb.Message.setOneofField(this, 12, proto.telemetry.TelemetryField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.telemetry.TelemetryField.prototype.hasFloatValue = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * repeated TelemetryField fields = 15;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.telemetry.TelemetryField>}
 */
proto.telemetry.TelemetryField.prototype.getFieldsList = function() {
  return /** @type{!Array.<!proto.telemetry.TelemetryField>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.telemetry.TelemetryField, 15));
};


/** @param {Array.<!proto.telemetry.TelemetryField>} value  */
proto.telemetry.TelemetryField.prototype.setFieldsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 15, value);
};


proto.telemetry.TelemetryField.prototype.clearFieldsList = function() {
  this.setFieldsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.telemetry.TelemetryGPBTable = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.telemetry.TelemetryGPBTable.repeatedFields_, null);
};
goog.inherits(proto.telemetry.TelemetryGPBTable, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.telemetry.TelemetryGPBTable.displayName = 'proto.telemetry.TelemetryGPBTable';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.telemetry.TelemetryGPBTable.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.telemetry.TelemetryGPBTable.prototype.toObject = function(opt_includeInstance) {
  return proto.telemetry.TelemetryGPBTable.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.telemetry.TelemetryGPBTable} msg The msg instance to transform.
 * @return {!Object}
 */
proto.telemetry.TelemetryGPBTable.toObject = function(includeInstance, msg) {
  var f, obj = {
    rowList: jspb.Message.toObjectList(msg.getRowList(),
    proto.telemetry.TelemetryRowGPB.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.telemetry.TelemetryGPBTable}
 */
proto.telemetry.TelemetryGPBTable.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.telemetry.TelemetryGPBTable;
  return proto.telemetry.TelemetryGPBTable.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.telemetry.TelemetryGPBTable} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.telemetry.TelemetryGPBTable}
 */
proto.telemetry.TelemetryGPBTable.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.telemetry.TelemetryRowGPB;
      reader.readMessage(value,proto.telemetry.TelemetryRowGPB.deserializeBinaryFromReader);
      msg.getRowList().push(value);
      msg.setRowList(msg.getRowList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.telemetry.TelemetryGPBTable} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.telemetry.TelemetryGPBTable.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.telemetry.TelemetryGPBTable.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.telemetry.TelemetryGPBTable.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getRowList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.telemetry.TelemetryRowGPB.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.telemetry.TelemetryGPBTable} The clone.
 */
proto.telemetry.TelemetryGPBTable.prototype.cloneMessage = function() {
  return /** @type {!proto.telemetry.TelemetryGPBTable} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated TelemetryRowGPB row = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.telemetry.TelemetryRowGPB>}
 */
proto.telemetry.TelemetryGPBTable.prototype.getRowList = function() {
  return /** @type{!Array.<!proto.telemetry.TelemetryRowGPB>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.telemetry.TelemetryRowGPB, 1));
};


/** @param {Array.<!proto.telemetry.TelemetryRowGPB>} value  */
proto.telemetry.TelemetryGPBTable.prototype.setRowList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.telemetry.TelemetryGPBTable.prototype.clearRowList = function() {
  this.setRowList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.telemetry.TelemetryRowGPB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.telemetry.TelemetryRowGPB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.telemetry.TelemetryRowGPB.displayName = 'proto.telemetry.TelemetryRowGPB';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.telemetry.TelemetryRowGPB.prototype.toObject = function(opt_includeInstance) {
  return proto.telemetry.TelemetryRowGPB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.telemetry.TelemetryRowGPB} msg The msg instance to transform.
 * @return {!Object}
 */
proto.telemetry.TelemetryRowGPB.toObject = function(includeInstance, msg) {
  var f, obj = {
    timestamp: msg.getTimestamp(),
    keys: msg.getKeys_asB64(),
    content: msg.getContent_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.telemetry.TelemetryRowGPB}
 */
proto.telemetry.TelemetryRowGPB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.telemetry.TelemetryRowGPB;
  return proto.telemetry.TelemetryRowGPB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.telemetry.TelemetryRowGPB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.telemetry.TelemetryRowGPB}
 */
proto.telemetry.TelemetryRowGPB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 10:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setKeys(value);
      break;
    case 11:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.telemetry.TelemetryRowGPB} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.telemetry.TelemetryRowGPB.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.telemetry.TelemetryRowGPB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.telemetry.TelemetryRowGPB.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = this.getKeys_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      10,
      f
    );
  }
  f = this.getContent_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      11,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.telemetry.TelemetryRowGPB} The clone.
 */
proto.telemetry.TelemetryRowGPB.prototype.cloneMessage = function() {
  return /** @type {!proto.telemetry.TelemetryRowGPB} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional uint64 timestamp = 1;
 * @return {number}
 */
proto.telemetry.TelemetryRowGPB.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.telemetry.TelemetryRowGPB.prototype.setTimestamp = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bytes keys = 10;
 * @return {!(string|Uint8Array)}
 */
proto.telemetry.TelemetryRowGPB.prototype.getKeys = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldProto3(this, 10, ""));
};


/**
 * optional bytes keys = 10;
 * This is a type-conversion wrapper around `getKeys()`
 * @return {string}
 */
proto.telemetry.TelemetryRowGPB.prototype.getKeys_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getKeys()));
};


/**
 * optional bytes keys = 10;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getKeys()`
 * @return {!Uint8Array}
 */
proto.telemetry.TelemetryRowGPB.prototype.getKeys_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getKeys()));
};


/** @param {!(string|Uint8Array)} value  */
proto.telemetry.TelemetryRowGPB.prototype.setKeys = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional bytes content = 11;
 * @return {!(string|Uint8Array)}
 */
proto.telemetry.TelemetryRowGPB.prototype.getContent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldProto3(this, 11, ""));
};


/**
 * optional bytes content = 11;
 * This is a type-conversion wrapper around `getContent()`
 * @return {string}
 */
proto.telemetry.TelemetryRowGPB.prototype.getContent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getContent()));
};


/**
 * optional bytes content = 11;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getContent()`
 * @return {!Uint8Array}
 */
proto.telemetry.TelemetryRowGPB.prototype.getContent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getContent()));
};


/** @param {!(string|Uint8Array)} value  */
proto.telemetry.TelemetryRowGPB.prototype.setContent = function(value) {
  jspb.Message.setField(this, 11, value);
};


goog.object.extend(exports, proto.telemetry);
